### ISSUE TITLE
Webpage does not display correctly in Linux (chromium-browser and firefox)

### ISSUE THREAD

**Issue by drvenabili** [ariddell/tatom#10]
Hello,

When visiting https://de.dariah.eu/tatom/topic_model_python.html, I encounter a display problem on my machine. 

I am running Elementary OS Freya 64 bits. The problem occurs on firefox and chromium-browser and in Firefox in a virtual Windows 7 machine.

Here is a screenshot: 
![screenshot from 2015-01-06 14 07 57](https://cloud.githubusercontent.com/assets/5579081/5628895/86655b94-95ad-11e4-84bc-3671175a8f19.png)

Thanking you,

**Comment by ariddell** [comment]
Thanks for taking the screenshot. I see the problem on my browser too. I'll look into it.

I'll also see if I can't render the project on github.io using standard CSS; that might be the source of the problem.

Thanks again for posting this. Corrections are very much appreciated.
