### ISSUE TITLE
SyntaxError: invalid syntax on Topic Modeling script

### ISSUE THREAD

**Issue by drvenabili** [ariddell/tatom#12]
Hello there, 

Once again thanks for the tutorial. I am following the one on Topic Modeling available [here](https://de.dariah.eu/tatom/topic_model_mallet.html). Nonetheless when I launch the python script (copy pasted and adapted in a .py file), I encounter this error:

```
simon@simon-thinkpad:~/dariah/data$ python reorder-for-matrix.py 
File "reorder-for-matrix.py", line 18
    docnum, docname, *values = line.rstrip().split('\t')
                     ^
SyntaxError: invalid syntax
```

with the "^" pointing to the star symbol. I'm no python expert so I don't really know what to change. 

Here's what I have launched, I basically copy-pasted your instructions, removed the steps numbering and changed the path to my doc-topics file:

``` python
import numpy as np
import itertools
import operator
import os

def grouper(n, iterable, fillvalue=None):
    "Collect data into fixed-length chunks or blocks"
    args = [iter(iterable)] * n
    return itertools.zip_longest(*args, fillvalue=fillvalue)

doctopic_triples = []

mallet_docnames = []

with open("doc-topics-hugo.txt") as f:
    f.readline()  # read one line in order to skip the header
    for line in f:
        docnum, docname, *values = line.rstrip().split('\t') # this is where the error happens
        mallet_docnames.append(docname)
        for topic, share in grouper(2, values):
            triple = (docname, int(topic), float(share))
            doctopic_triples.append(triple)

# sort the triples
# triple is (docname, topicnum, share) so sort(key=operator.itemgetter(0,1))
# sorts on (docname, topicnum) which is what we want
doctopic_triples = sorted(doctopic_triples, key=operator.itemgetter(0,1))

# sort the document names rather than relying on MALLET's ordering
mallet_docnames = sorted(mallet_docnames)

# collect into a document-term matrix
num_docs = len(mallet_docnames)

num_topics = len(doctopic_triples) // len(mallet_docnames)

# the following works because we know that the triples are in sequential order
doctopic = np.zeros((num_docs, num_topics))

for triple in doctopic_triples:
    docname, topic, share = triple
    row_num = mallet_docnames.index(docname)
    doctopic[row_num, topic] = share
```

Thanks in advance.

**Comment by ariddell** [comment]
Hi @faustusdotbe. Thanks for the report. That particular problem will be solved if you use Python 3. It looks like you're using Python 2.

If the problem keeps occurring, please reopen the issue.

**Comment by drvenabili** [comment]
I am indeed using python 2. Will try with python 3, thanks!

On 24 February 2015 at 18:14, Allen Riddell notifications@github.com
wrote:

> Hi @faustusdotbe https://github.com/faustusdotbe. Thanks for the
> report. That particular problem will be solved if you use Python 3. It
> looks like you're using Python 2.
> 
> If the problem keeps occurring, please reopen the issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ariddell/tatom/issues/12#issuecomment-75799585.

## 

Simon Hengchen
