### ISSUE TITLE
Page not found https://de.dariah.eu/tatom/

### ISSUE THREAD

**Issue by hosamshahin** [ariddell/tatom#15]
https://de.dariah.eu/tatom/topic_model_python.html

**Comment by ariddell** [comment]
@christofs Any idea?

**Comment by christofs** [comment]
I noticed this as well hand have notified DARIAH already. They migrated some stuff recently and will look into it.

**Comment by mtllr** [comment]
Hi, same problem here. 

Would love to have the material back on line, it is an awesome tutorial!

**Comment by christofs** [comment]
Should be fixed now!
