### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by ericleasemorgan** [ariddell/tatom#17]
I am working through the code to play with MALLET output, and I get a syntax error here:

  docnum, docname, *values = line.rstrip().split('\t')

Python does not seem to like the *. How can I resolve this issue?

**Comment by ariddell** [comment]
Try Python 3. If that doesn't work, tell me what the contents of `line` are.

**Comment by ericleasemorgan** [comment]
I resolved this error, thank you. If I remember correctly, I split the line by hand, and then I subplot it again. All is good on my end:

# parse the database of previously created topics
with open( database ) as f :
	f.readline()
	for line in f :
		values   = line.rstrip().split( '\t' )	
		index    = values.pop( 0 )
		document = values.pop( 0 )	
		documents.append( document )
		for topic, share in grouper( 2, values ) : triples.append( ( document, int( topic ), float( share ) ) )
